server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
  application:
    name: fastview-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nwct.kshost.cn:3306/db_FastView?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Qq2548706536@
  cloud:
    nacos:
      discovery:
        server-addr: nwct.kshost.cn:8848
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

